FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./

EXPOSE 5000
EXPOSE 5001

CMD ["dotnet", "watch", "run", "-lp", "http", "--urls", "http://0.0.0.0:5000"]