FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

COPY *.csproj ./
RUN dotnet restore

COPY . ./

EXPOSE 5000
EXPOSE 5001