services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - session-db
      - backend
      - server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - AUTH_URL=http://server:9000
      - NEXT_PUBLIC_AUTH_URL=http://localhost:9000
      - SESSION_DB_URL=postgres://postgres:postgres@session-db:5432/sessions
      - API_URL=http://backend:5000
