name: Frontend PR

on:
  pull_request:
    branches: ["main"]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    env:
      BETTER_AUTH_SECRET: SZXsmzu6o4PpHcGT7LIQFyt0lQ8AfLlo
      BETTER_AUTH_URL: http://localhost:3000 #Base URL of your app
      AUTH_URL: http://localhost:9000 #Base URL of your authentik instance
      NEXT_PUBLIC_AUTH_URL: http://localhost:9000 #Base URL of your authentik instance
      NEXT_TELEMETRY_DISABLED: 1
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build -- --no-lint
      - name: Run Tests
        run: npm run test:coverage
